### PR TITLE
Massive renaming

### PR DESCRIPTION
**Pull request by rec**
All right!

DON'T pull this into your repo to see if it works - though I think it's in a good state, you need to be able to test stuff from "random strangers" before checking it in!

Do you know how to get a copy of this yourself to test?

I'm going to make some comments also in the pull request to show you what's going on...

### CODE REVIEW

**Comment by rec** [comment]
I pushed a "fixup" commit.  

Before you actually merge, I will "autosquash" that commit into the original one using `git rebase`.

Off to work on other things for a bit, let me know!

**Comment by testcaseone** [comment]
I will "autosquash" that commit into the original one using git rebase.

No idea what that means :). But I won't merge it. But i'll try to pull it into a new project and test it.

**Comment by rec** [comment]
Basically, it means "I can glue these two commits into one automatically!"

:-D

Let me know how it goes.  Just finished soldering six cables and they all
worked!  (haven't done much soldering before...)

On Sat, Aug 29, 2015 at 4:37 PM, Tim <notifications@github.com> wrote:

> I will "autosquash" that commit into the original one using git rebase.
>
> No idea what that means :). But I won't merge it. But i'll try to pull it
> into a new project and test it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/testcaseone/vbat/pull/11#issuecomment-136047721>.
>



-- 
     /t

http://radio.swirly.com - art music radio 24/7 366/1000

**Comment by testcaseone** [comment]
Okay, do your glue thing and maybe give me a tip how i can pull that to test it. I thought you would have all these changes on your repository and i could just pull that, but that isn't the case.

Incidentally soldering is something i'm way better in than programming :)

It's well after midnight, i look at your changes tomorrow morning. Have a good night and thanks again for your help

**Comment by rec** [comment]
Oh, github has a good article!

https://help.github.com/articles/checking-out-pull-requests-locally/

Too late about the soldering, I did it all!  Seemed to work out. Wish I had
heatshrink, but the Xtreme tape I have will probably do the job.

On Sat, Aug 29, 2015 at 6:44 PM, Tim <notifications@github.com> wrote:

> Okay, do your glue thing and maybe give me a tip how i can pull that to
> test it. I thought you would have all these changes on your repository and
> i could just pull that, but that isn't the case.
>
> Incidentally soldering is something i'm way better in than programming :)
>
> It's well after midnight, i look at your changes tomorrow morning. Have a
> good night and thanks again for your help
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/testcaseone/vbat/pull/11#issuecomment-136058640>.
>



-- 
     /t

http://radio.swirly.com - art music radio 24/7 366/1000

**Comment by testcaseone** [comment]
Had to correct some paths and change main to Main in the vbat.py. The folder perhaps_remove is deleted. And the test-session "nn" was changed to "test".
I also changed it so that you don't need a camera if you test the program with "python vbat.py -n test -i images/test.jpeg".
I hope you get the program to work on you side so that you can try mp without being blind to your changes :)

**Comment by rec** [comment]
Good stuff! Makes me happy!

I'll have an hour or two later this afternoon to fiddle.

Overall I'll have time for a couple of weeks to do a little leisurely work
every few days.

As I get to a music show September 26 my time will be short but I hope to
hit the goal of putting in multiprocessing and then "retire" to a pure
consultatory role.

Hope you're having a good weekend!

On Sun, Aug 30, 2015 at 7:44 AM, Tim <notifications@github.com> wrote:

> Had to correct some paths and change main to Main in the vbat.py. The
> folder perhaps_remove is deleted. And the test-session "nn" was changed to
> "test".
> I also changed it so that you don't need a camera if you test the program
> with "python vbat.py -n test -i images/test.jpeg".
> I hope you get the program to work on you side so that you can try mp
> without being blind to your changes :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/testcaseone/vbat/pull/11#issuecomment-136130542>.
>



-- 
     /t

http://radio.swirly.com - art music radio 24/7 366/1000

**Comment by testcaseone** [comment]
Very glad to hear you'll still be there if i have questions, that's very nice :).
I'll be working on the GUI and the Hardware the next days and my friend is working on the controls. 
Maybe We're able to test everything in a few days or so. I'll make a video of it, so you can see what you are working for.

How would i go about crediting the three of us for our work in the code? There would be some rules for that too, right?

Wish you a good weekend too.

**Comment by rec** [comment]
Oh, don't worry about credit - the github process does that - but if you
wanted to do it, you could put it into the README.md.  :-)

off for brunch, would love to see the video!

On Sun, Aug 30, 2015 at 12:01 PM, Tim <notifications@github.com> wrote:

> Very glad to hear you'll still be there if i have questions, that's very
> nice :).
> I'll be working on the GUI and the Hardware the next days and my friend is
> working on the controls.
> Maybe We're able to test everything in a few days or so. I'll make a video
> of it, so you can see what you are working for.
>
> How would i go about crediting the three of us for our work in the code?
> There would be some rules for that too, right?
>
> Wish you a good weekend too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/testcaseone/vbat/pull/11#issuecomment-136155854>.
>



-- 
     /t

http://radio.swirly.com - art music radio 24/7 366/1000

**Pull request merged**
